import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:nfc_app/constants/app_colors.dart';
import 'package:nfc_app/constants/app_spacing.dart';
import 'package:nfc_app/constants/app_textstyles.dart';

class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Theme.of(context).colorScheme.surface,
      appBar: AppBar(
        automaticallyImplyLeading: true,
        centerTitle: true,
        backgroundColor: Colors.white,
        // leading: const SizedBox(),
        title: Text(
          "Privacy Policy",
          style: AppTextStyle.heading2,
        ),
      ),
      body: SingleChildScrollView(
        padding: XPadding.horizontal16,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Last updated: July 30, 2024',
              style: AppTextStyle.bodyText,
            ),
            const YGap(value: 16),
            Text(
                'This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. '
                'We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.',
                style: AppTextStyle.bodyText),
            const YGap(value: 16),
            Text(
              'Definitions',
              style: GoogleFonts.inter(
                textStyle: const TextStyle(
                  fontWeight: FontWeight.w400,
                  fontSize: 18.0,
                  color: AppColors.primaryTextColor,
                ),
              ),
            ),
            const YGap(value: 8),
            _buildDefinition('Account',
                'means a unique account created for You to access our Service or parts of our Service.'),
            _buildDefinition('Affiliate',
                'means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.'),
            _buildDefinition('Application',
                'refers to Translate Buddy, the software program provided by the Company.'),
            _buildDefinition('Company',
                'referred to as either "the Company", "We", "Us" or "Our" in this Agreement refers to Translate Buddy.'),
            _buildDefinition('Country', 'refers to: Nigeria'),
            _buildDefinition('Service', 'refers to the Application.'),
            _buildDefinition('Service Provider',
                'means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.'),
            _buildDefinition('Usage Data',
                'refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).'),
            _buildDefinition('You',
                'means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.'),
            const YGap(value: 16),
            Text(
              'Collecting and Using Your Personal Data',
              style: GoogleFonts.inter(
                textStyle: const TextStyle(
                  fontWeight: FontWeight.w400,
                  fontSize: 18.0,
                  color: AppColors.primaryTextColor,
                ),
              ),
            ),
            const YGap(value: 8),
            Text(
              'Types of Data Collected',
              style: AppTextStyle.bodyText,
            ),
            const YGap(value: 8),
            Text(
                'Personal Data\nWhile using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:',
                style: AppTextStyle.bodyText),
            const YGap(value: 8),
            Text('• Usage Data', style: AppTextStyle.bodyText),
            const YGap(value: 16),
            Text(
              'Usage Data',
              style: AppTextStyle.bodyText,
            ),
            const YGap(value: 8),
            Text(
                'Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device\'s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.\n'
                'When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.\n'
                'We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.',
                style: AppTextStyle.bodyText),
            const YGap(value: 16),
            Text(
              'Use of Your Personal Data',
              style: GoogleFonts.inter(
                textStyle: const TextStyle(
                  fontWeight: FontWeight.w400,
                  fontSize: 18.0,
                  color: AppColors.primaryTextColor,
                ),
              ),
            ),
            const YGap(value: 8),
            Text(
                'The Company may use Personal Data for the following purposes:',
                style: AppTextStyle.bodyText),
            _buildUsage('To provide and maintain our Service',
                'including to monitor the usage of our Service.'),
            _buildUsage('To manage Your Account',
                'to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.'),
            _buildUsage('For the performance of a contract',
                'the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.'),
            _buildUsage(
                'To provide You with news, special offers and general information',
                'about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.'),
            _buildUsage('To manage Your requests',
                'To attend and manage Your requests to Us.'),
            _buildUsage('For other purposes',
                'We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.'),
            const YGap(value: 16),
            Text(
                'We may share Your personal information in the following situations:',
                style: AppTextStyle.bodyText),
            _buildSharing('With Service Providers',
                'We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.'),
            _buildSharing('For business transfers',
                'We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.'),
            _buildSharing('With Affiliates',
                'We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.'),
            _buildSharing('With business partners',
                'We may share Your information with Our business partners to offer You certain products, services or promotions.'),
            _buildSharing('With other users',
                'when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.'),
            _buildSharing('With Your consent',
                'We may disclose Your personal information for any other purpose with Your consent.'),
            const YGap(value: 16),
            Text(
              'Retention of Your Personal Data',
              style: GoogleFonts.inter(
                textStyle: const TextStyle(
                  fontWeight: FontWeight.w400,
                  fontSize: 18.0,
                  color: AppColors.primaryTextColor,
                ),
              ),
            ),
            const YGap(value: 8),
            Text(
                'The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies. '
                'The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.',
                style: AppTextStyle.bodyText),
            const YGap(value: 16),
            Text(
              'Transfer of Your Personal Data',
              style: GoogleFonts.inter(
                textStyle: const TextStyle(
                  fontWeight: FontWeight.w400,
                  fontSize: 18.0,
                  color: AppColors.primaryTextColor,
                ),
              ),
            ),
            const YGap(value: 8),
            Text(
                'Your information, including Personal Data, is processed at the Company\'s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.\n'
                'Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.\n'
                'The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.',
                style: AppTextStyle.bodyText),
            const YGap(value: 16),
            Text(
              'Security of Your Personal Data',
              style: GoogleFonts.inter(
                textStyle: const TextStyle(
                  fontWeight: FontWeight.w400,
                  fontSize: 18.0,
                  color: AppColors.primaryTextColor,
                ),
              ),
            ),
            const YGap(value: 8),
            Text(
                'The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.',
                style: AppTextStyle.bodyText),
            const YGap(value: 16),
            Text(
              'Changes to this Privacy Policy',
              style: GoogleFonts.inter(
                textStyle: const TextStyle(
                  fontWeight: FontWeight.w400,
                  fontSize: 18.0,
                  color: AppColors.primaryTextColor,
                ),
              ),
            ),
            const YGap(value: 8),
            Text(
                'We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.\n'
                'We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.\n'
                'You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.',
                style: AppTextStyle.bodyText),
            const YGap(value: 16),
            Text(
              'Contact Us',
              style: GoogleFonts.inter(
                textStyle: const TextStyle(
                  fontWeight: FontWeight.w400,
                  fontSize: 18.0,
                  color: AppColors.primaryTextColor,
                ),
              ),
            ),
            const YGap(value: 8),
            Text(
                'If you have any questions about this Privacy Policy, You can contact us:\n'
                'By email: mysterymann.01552@',
                style: AppTextStyle.bodyText),
          ],
        ),
      ),
    );
  }

  Widget _buildDefinition(String term, String definition) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 4.0),
      child: RichText(
        text: TextSpan(
          style: AppTextStyle.bodyText,
          children: [
            TextSpan(
              text: '$term ',
              style: AppTextStyle.bodyText,
            ),
            TextSpan(text: definition),
          ],
        ),
      ),
    );
  }

  Widget _buildUsage(String purpose, String description) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 4.0),
      child: RichText(
        text: TextSpan(
          style: AppTextStyle.bodyText,
          children: [
            TextSpan(
              text: '$purpose: ',
              style: const TextStyle(fontWeight: FontWeight.bold),
            ),
            TextSpan(text: description),
          ],
        ),
      ),
    );
  }

  Widget _buildSharing(String entity, String description) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 4.0),
      child: RichText(
        text: TextSpan(
          style: AppTextStyle.bodyText,
          children: [
            TextSpan(
              text: '$entity: ',
              style: AppTextStyle.bodyText,
            ),
            TextSpan(text: description),
          ],
        ),
      ),
    );
  }
}
